/**
 * Interactive database scripts phase — behavior contract.
 *
 * `dxg add database` must let the user decide which database scripts land
 * in package.json, after the database setup itself:
 *
 *   provider / skills → dependencies → prisma init → scripts phase → summary
 *
 * The phase is owned entirely by the database generator (this domain) —
 * NOT by apps/cli add.ts (dispatch only) and NOT by a new package.
 *
 * Contract under test:
 * - A `databaseScripts` select (recommended | customize | skip) is asked
 *   only in interactive mode, after the provider/skills answers.
 * - "recommended" adds the recommended set (db:generate, db:push, db:studio).
 * - "customize" shows a multiselect of provider-appropriate scripts; only
 *   the selected ones are added.
 * - "skip" leaves package.json untouched and reports the skip.
 * - Non-interactive / dry-run / CI defaults to the recommended set (the
 *   generator stays deterministic without a TTY).
 * - Existing scripts are never overwritten or duplicated: identical →
 *   already-exists, different command → conflict preserved without force.
 * - Re-running is idempotent.
 * - Unrelated package.json fields survive.
 * - Cancellation propagates the Clack cancel symbol (existing convention).
 * - PlanetScale never offers db:migrate (prisma migrate dev unsupported on
 *   Vitess); the knowledge lives in providerData.
 */

import {
  describe,
  test,
  expect,
  vi,
  beforeEach,
  afterEach,
  beforeAll,
  type Mock,
} from "vitest";
import { Logger } from "@dxgjs/logger";
import * as fs from "@dxgjs/fs";
import { render as realRender } from "@dxgjs/templates";
import {
  note as noteMock,
  prompt as promptMock,
  multiselect as multiselectMock,
  cancel as cancelMock,
} from "@dxgjs/prompts";
import * as path from "path";
import * as os from "os";

vi.mock("@dxgjs/prompts", async () => {
  const actual = await vi.importActual("@dxgjs/prompts");
  return {
    ...actual,
    prompt: vi.fn(),
    multiselect: vi.fn(),
    intro: vi.fn(),
    outro: vi.fn(),
    isCancel: vi.fn((value: unknown) => value === Symbol.for("clack:cancel")),
    cancel: vi.fn(),
    spinner: vi.fn().mockReturnValue({
      start: vi.fn(),
      stop: vi.fn(),
    }),
    note: vi.fn(),
  };
});

vi.mock("@dxgjs/fs", async () => {
  const actual = await vi.importActual<typeof import("@dxgjs/fs")>("@dxgjs/fs");
  // Hoisted store. Mock implementations MUST close over these maps instead of
  // relying on `this`: several call sites invoke these functions without a
  // receiver (same rationale as package-manifest.test.ts).
  const _files = new Map<string, string>();
  const _directories = new Set<string>();
  // The exact prisma7.config.ts content written by `prisma init` 7.10.0
  // (non-bun runtime, prisma identity) — verified against the installed
  // CLI bundle. Exposed so tests can pre-seed user-modified variants.
  const _prismaInitConfig = [
    "// This file was generated by Prisma, and assumes you have installed the following:",
    "// npm install --save-dev prisma dotenv",
    'import "dotenv/config";',
    'import { defineConfig } from "prisma/config";',
    "",
    "export default defineConfig({",
    '  schema: "prisma/schema.prisma",',
    "  migrations: {",
    '    path: "prisma/migrations",',
    "  },",
    "  datasource: {",
    '    url: process.env["DATABASE_URL"],',
    "  },",
    "});",
    "",
  ].join("\n");
  const _mock = {
    ...actual,
    _files,
    _directories,
    _prismaInitConfig,
    pathExists: vi.fn().mockImplementation(async (filePath: string) => {
      if (_files.has(filePath) || _directories.has(filePath)) {
        return true;
      }
      return actual.pathExists(filePath);
    }),
    readFile: vi.fn().mockImplementation(
      async (filePath: string, options?: any) => {
        if (_files.has(filePath)) {
          return _files.get(filePath);
        }
        return actual.readFile(filePath, options);
      },
    ),
    writeFile: vi.fn().mockImplementation(
      async (filePath: string, data: string | Buffer) => {
        _files.set(filePath, data.toString());
        const dir = filePath.split("/").slice(0, -1).join("/");
        if (dir) {
          _directories.add(dir);
        }
        return undefined;
      },
    ),
    stat: vi.fn().mockImplementation(async (filePath: string) => {
      if (_files.has(filePath)) {
        return { isDirectory: () => false, isFile: () => true };
      }
      if (_directories.has(filePath)) {
        return { isDirectory: () => true, isFile: () => false };
      }
      return actual.stat(filePath);
    }),
    mkdir: vi.fn().mockImplementation(async (filePath: string) => {
      _directories.add(filePath);
      const parentDir = filePath.split("/").slice(0, -1).join("/");
      if (parentDir) {
        _directories.add(parentDir);
      }
      return undefined;
    }),
    readJson: vi.fn().mockImplementation(async (filePath: string) => {
      const content = _files.get(filePath);
      if (content !== undefined) {
        return JSON.parse(content);
      }
      return actual.readJson(filePath);
    }),
    writeJson: vi.fn().mockImplementation(
      async (
        filePath: string,
        data: unknown,
        options?: { spaces?: number },
      ) => {
        _files.set(
          filePath,
          JSON.stringify(data, null, options?.spaces ?? 2),
        );
        return undefined;
      },
    ),
    executeCommand: vi.fn().mockImplementation(
      async (command: string, args: string[] = []) => {
        // Simulate the package manager persisting installed dependencies
        // into package.json (same semantics as package-manifest.test.ts).
        if (command === "npm" && args[0] === "install") {
          const dev = args[1] === "-D";
          const packages = dev ? args.slice(2) : args.slice(1);
          const manifest = JSON.parse(
            _files.get("package.json") ?? "{}",
          ) as Record<string, any>;
          const section = dev
            ? (manifest.devDependencies ??= {})
            : (manifest.dependencies ??= {});
          for (const spec of packages) {
            const at = spec.lastIndexOf("@");
            const name = at > 0 ? spec.slice(0, at) : spec;
            section[name] = at > 0 ? spec.slice(at + 1) : "*";
          }
          _files.set("package.json", JSON.stringify(manifest, null, 2));
        }
        // Simulate `prisma init` (prisma@7.10.0, non-bun): it owns and
        // writes the root prisma7.config.ts plus the prisma/ scaffolding.
        // Only when the project doesn't already have one — mirroring the
        // real CLI, which refuses to run in an existing Prisma project.
        if (
          command === "npx" &&
          args[0] === "prisma@7" &&
          args[1] === "init" &&
          !_files.has("prisma7.config.ts")
        ) {
          _files.set("prisma7.config.ts", _prismaInitConfig);
          _directories.add("prisma");
        }
        return undefined;
      },
    ),
  };
  return _mock;
});

vi.mock("@antfu/ni", () => {
  return {
    parseNi: vi.fn().mockReturnValue("npm"),
    parseNlx: vi.fn().mockReturnValue("npx"),
    getCliCommand: vi
      .fn()
      .mockImplementation(async (_parseFn: unknown, args: string[]) => {
        if (!args || args.length === 0) {
          return { command: "npm", args: [] };
        }
        if (args[0] === "prisma@7" && args[1] === "init") {
          return { command: "npx", args: [...args] };
        }
        if (args[0] === "-D") {
          return { command: "npm", args: ["install", "-D", ...args.slice(1)] };
        }
        return { command: "npm", args: ["install", ...args] };
      }),
  };
});

vi.mock("@dxgjs/templates", async () => {
  const actual =
    await vi.importActual<typeof import("@dxgjs/templates")>("@dxgjs/templates");
  return {
    ...actual,
    render: vi.fn(actual.render),
  };
});

let databaseGenerator: any;

beforeAll(async () => {
  const indexModule = await import("./index");
  databaseGenerator = indexModule.default;
});

const fsMockStore = fs as unknown as {
  _files: Map<string, string>;
  _directories: Set<string>;
  _prismaInitConfig: string;
};

const CANCEL = Symbol.for("clack:cancel");

/** A realistic fresh Next.js project manifest (unrelated fields intact). */
const MY_APP_PACKAGE_JSON = {
  name: "my-app",
  version: "0.1.0",
  private: true,
  scripts: {
    dev: "next dev",
    build: "next build",
    start: "next start",
    lint: "eslint",
  },
  dependencies: {
    next: "16.2.12",
    react: "19.2.4",
    "react-dom": "19.2.4",
  },
};

async function seedProject(manifest: unknown = MY_APP_PACKAGE_JSON) {
  await fs.writeFile("package.json", JSON.stringify(manifest, null, 2), "utf8");
}

function readManifestFromDisk(): Record<string, any> {
  const raw = fsMockStore._files.get("package.json");
  expect(raw).toBeDefined();
  return JSON.parse(raw!);
}

/** The Prisma 7 config file as it exists on disk. */
function readPrismaConfig(): string {
  const raw = fsMockStore._files.get("prisma7.config.ts");
  expect(raw).toBeDefined();
  return raw!;
}

function makeContext(overrides: Record<string, unknown> = {}) {
  return {
    logger: {
      info: vi.fn(),
      error: vi.fn(),
      warn: vi.fn(),
      debug: vi.fn(),
    } as unknown as Logger,
    fs,
    templates: {
      render: vi.fn(realRender),
    },
    awareness: {
      projectRoot: ".",
      workspaceRoot: ".",
      framework: { name: "next-app", detected: true },
      language: { name: "typescript", detected: true },
      packageManager: "pnpm",
      styling: {
        name: "tailwindcss",
        detected: true,
        version: "v4",
        configFile: null,
      },
      capabilities: {
        hasTests: false,
        hasLinting: true,
        hasFormatter: false,
        hasCI: false,
        hasDocker: false,
      },
      packageJson: JSON.parse(JSON.stringify(MY_APP_PACKAGE_JSON)),
    },
    dryRun: false,
    force: false,
    nonInteractive: false,
    ...overrides,
  };
}

function notes(): string[] {
  return (noteMock as Mock).mock.calls.map((call) => String(call[0]));
}

function operationSummary(runs = 1): string {
  const summaryNotes = notes();
  expect(summaryNotes.length).toBe(runs);
  return summaryNotes[runs - 1];
}

/** The databaseScripts question asked by the interactive phase. */
function scriptsQuestion(): {
  name: string;
  type: string;
  message: string;
  choices: Array<{ name: string; value: string }>;
  default?: unknown;
} | undefined {
  const allCalls = (promptMock as Mock).mock.calls;
  for (const call of allCalls) {
    const questions = call[0] as Array<Record<string, unknown>>;
    const found = questions?.find?.((q) => q.name === "databaseScripts");
    if (found) return found as ReturnType<typeof scriptsQuestion>;
  }
  return undefined;
}

describe("interactive database scripts phase", () => {
  let originalCwd: string;
  let tempDir: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    tempDir = path.join(
      os.tmpdir(),
      `dxg-scripts-test-${Date.now()}-${Math.random()
        .toString(36)
        .substring(2, 15)}`,
    );
    fs.mkdirSync(tempDir, { recursive: true });
    process.chdir(tempDir);
    vi.clearAllMocks();
    fsMockStore._files.clear();
    fsMockStore._directories.clear();
    delete process.env.CI;
  });

  afterEach(() => {
    process.chdir(originalCwd);
    fs.rmSync(tempDir, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  test("asks the databaseScripts question after provider/skills, recommended first", async () => {
    await seedProject();
    // One prompt() call collects every missing answer (provider, skills,
    // databaseScripts) — a single queued response covers it.
    (promptMock as unknown as Mock).mockResolvedValueOnce({
      provider: "postgresql",
      installPrismaSkills: false,
      databaseScripts: "recommended",
    });

    await databaseGenerator.run({}, makeContext());

    // The phase question is asked interactively...
    const question = scriptsQuestion();
    expect(question).toBeDefined();
    expect(question!.type).toBe("select");
    expect(question!.message).toMatch(/database scripts/i);
    // Recommended is the default choice.
    expect(question!.default).toBe("recommended");
    const values = question!.choices.map((c) => c.value);
    expect(values).toContain("recommended");
    expect(values).toContain("customize");
    expect(values).toContain("skip");
  });

  test("recommended: adds exactly the recommended set (db:generate, db:push, db:studio)", async () => {
    await seedProject();

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "recommended" },
      makeContext(),
    );

    const final = readManifestFromDisk();
    expect(final.scripts["db:generate"]).toBe("prisma generate");
    expect(final.scripts["db:push"]).toBe("prisma db push");
    expect(final.scripts["db:studio"]).toBe("prisma studio");
    // The recommended set is deliberately minimal.
    expect(final.scripts["db:migrate"]).toBeUndefined();
    expect(final.scripts["db:pull"]).toBeUndefined();
    expect(final.scripts["db:seed"]).toBeUndefined();
    expect(final.scripts["db:reset"]).toBeUndefined();
    // Never prompted: the answer came from the CLI answers.
    expect(promptMock).not.toHaveBeenCalled();
  });

  test("customize: only the scripts selected in the multiselect are added", async () => {
    await seedProject();
    (promptMock as unknown as Mock).mockResolvedValue({
      databaseScripts: "customize",
    });
    (multiselectMock as unknown as Mock).mockResolvedValue([
      "db:generate",
      "db:migrate",
    ]);

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false },
      makeContext(),
    );

    // The multiselect offers the provider-appropriate scripts with hints.
    const multiselectCall = (multiselectMock as Mock).mock.calls[0];
    expect(multiselectCall).toBeDefined();
    // promptCustomScripts passes a single options object (not message+opts).
    const options = multiselectCall[0];
    expect(String(options.message)).toMatch(/database scripts/i);
    const optionValues = options.options.map(
      (o: { value: string }) => o.value,
    );
    expect(optionValues).toContain("db:generate");
    expect(optionValues).toContain("db:push");
    expect(optionValues).toContain("db:studio");
    expect(optionValues).toContain("db:migrate");
    expect(optionValues).toContain("db:pull");
    // Each option communicates what the script does.
    const generate = options.options.find(
      (o: { value: string }) => o.value === "db:generate",
    );
    expect(String(generate.hint || generate.label)).toMatch(/prisma client/i);

    const final = readManifestFromDisk();
    expect(final.scripts["db:generate"]).toBe("prisma generate");
    expect(final.scripts["db:migrate"]).toBe("prisma migrate dev");
    expect(final.scripts["db:push"]).toBeUndefined();
    expect(final.scripts["db:studio"]).toBeUndefined();
  });

  test("skip: package.json is untouched by the scripts phase and the skip is reported", async () => {
    await seedProject();

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "skip" },
      makeContext(),
    );

    // The scripts phase never wrote the manifest (dependency installs by the
    // package manager legitimately change it — those are not script writes).
    expect(fs.writeJson).not.toHaveBeenCalled();
    const final = readManifestFromDisk();
    // No db:* scripts were added.
    const dbScriptKeys = Object.keys(final.scripts ?? {}).filter((k) =>
      k.startsWith("db:"),
    );
    expect(dbScriptKeys).toEqual([]);
    // Pre-existing scripts and fields intact.
    expect(final.scripts.dev).toBe("next dev");
    expect(final.name).toBe("my-app");
    const summary = operationSummary();
    expect(summary.toLowerCase()).toContain("skip");
  });

  test("existing identical scripts are reported as already existing, never duplicated or overwritten", async () => {
    const manifest = {
      ...MY_APP_PACKAGE_JSON,
      scripts: {
        ...MY_APP_PACKAGE_JSON.scripts,
        "db:generate": "prisma generate",
      },
    };
    await seedProject(manifest);

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "recommended" },
      makeContext(manifest),
    );

    const final = readManifestFromDisk();
    // Exactly one db:generate, still the same command.
    expect(final.scripts["db:generate"]).toBe("prisma generate");
    const dbScriptKeys = Object.keys(final.scripts).filter((k) =>
      k.startsWith("db:"),
    );
    expect(dbScriptKeys.filter((k) => k === "db:generate")).toHaveLength(1);
    // The summary distinguishes added vs already-existing.
    const summary = operationSummary();
    expect(summary).toContain("db:push");
    expect(summary).toContain("db:generate");
    expect(summary.toLowerCase()).toContain("already exists");
  });

  test("user-defined scripts with a different command are preserved and reported as conflicts", async () => {
    const manifest = {
      ...MY_APP_PACKAGE_JSON,
      scripts: {
        ...MY_APP_PACKAGE_JSON.scripts,
        "db:generate": "prisma generate --custom",
      },
    };
    await seedProject(manifest);

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "recommended" },
      makeContext(manifest),
    );

    const final = readManifestFromDisk();
    expect(final.scripts["db:generate"]).toBe("prisma generate --custom");
    expect(final.scripts["db:push"]).toBe("prisma db push");
    const summary = operationSummary();
    expect(summary.toLowerCase()).toContain("conflict");
    expect(summary).toContain("prisma generate --custom");
  });

  test("re-running is idempotent (second run adds nothing new)", async () => {
    await seedProject();

    const answers = {
      provider: "postgresql",
      installPrismaSkills: false,
      databaseScripts: "recommended",
    };
    const context = makeContext();
    await databaseGenerator.run(answers, context);
    const writesAfterFirst = (fs.writeJson as Mock).mock.calls.length;
    const first = readManifestFromDisk();

    await databaseGenerator.run(answers, context);
    const second = readManifestFromDisk();

    // No second write: identical scripts → skipped.
    expect((fs.writeJson as Mock).mock.calls.length).toBe(writesAfterFirst);
    expect(second).toEqual(first);
    const secondSummary = operationSummary(2);
    expect(secondSummary.toLowerCase()).toContain("already exists");
  });

  test("unrelated package.json fields and existing scripts remain intact", async () => {
    await seedProject();

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "recommended" },
      makeContext(),
    );

    const final = readManifestFromDisk();
    expect(final.name).toBe("my-app");
    expect(final.version).toBe("0.1.0");
    expect(final.private).toBe(true);
    expect(final.scripts.dev).toBe("next dev");
    expect(final.scripts.build).toBe("next build");
    expect(final.dependencies.next).toBe("16.2.12");
    // DXG-installed dependencies survive the write-back.
    expect(final.devDependencies.prisma).toBe("7.10.0");
    expect(final.dependencies["@prisma/client"]).toBe("7.10.0");
  });

  test("cancellation during the phase propagates the Clack cancel symbol", async () => {
    await seedProject();
    // @dxgjs/prompts' prompt() throws the cancel symbol when a primitive
    // resolves with it — simulate the user cancelling the scripts question.
    (promptMock as unknown as Mock).mockRejectedValueOnce(CANCEL);

    // The mocked isCancel recognizes the stand-in symbol; cancellation must
    // propagate (the CLI turns it into a clean exit).
    await expect(
      databaseGenerator.run(
        { provider: "postgresql", installPrismaSkills: false },
        makeContext(),
      ),
    ).rejects.toBe(CANCEL);
    // The Clack cancellation boundary was reached.
    expect(cancelMock).toHaveBeenCalledWith("Operation cancelled");
  });

  test("PlanetScale never offers db:migrate (prisma migrate dev unsupported on Vitess)", async () => {
    await seedProject();
    (promptMock as unknown as Mock).mockResolvedValue({
      databaseScripts: "customize",
    });
    (multiselectMock as unknown as Mock).mockResolvedValue([]);

    await databaseGenerator.run(
      { provider: "planetscale", installPrismaSkills: false },
      makeContext(),
    );

    const psOptions = (multiselectMock as Mock).mock.calls[0][0];
    const values = psOptions.options.map((o: { value: string }) => o.value);
    expect(values).not.toContain("db:migrate");
    // The rest of the catalogue is still offered.
    expect(values).toContain("db:generate");
    expect(values).toContain("db:push");
  });

  test("non-interactive mode defaults to the recommended set without prompting", async () => {
    await seedProject();

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false },
      makeContext({ nonInteractive: true }),
    );

    expect(promptMock).not.toHaveBeenCalled();
    const final = readManifestFromDisk();
    expect(final.scripts["db:generate"]).toBe("prisma generate");
    expect(final.scripts["db:push"]).toBe("prisma db push");
    expect(final.scripts["db:studio"]).toBe("prisma studio");
  });

  test("dry-run never prompts and never mutates package.json", async () => {
    await seedProject();
    const before = fsMockStore._files.get("package.json");

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false },
      makeContext({ dryRun: true }),
    );

    expect(promptMock).not.toHaveBeenCalled();
    expect(multiselectMock).not.toHaveBeenCalled();
    expect(fs.writeJson).not.toHaveBeenCalled();
    expect(fsMockStore._files.get("package.json")).toBe(before);
    const summary = operationSummary();
    expect(summary.toLowerCase()).toContain("db:generate");
  });

  test("final generator state stays valid (verify passes, outro rendered)", async () => {
    await seedProject();

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "recommended" },
      makeContext(),
    );

    // lib/prisma.ts (DXG-owned template) was created — the generator's
    // verification step passed.
    expect(fsMockStore._files.has("lib/prisma.ts")).toBe(true);
    // A single coherent Operation Summary was rendered.
    expect(notes().length).toBe(1);
  });

  test("db:seed is offered in customize (optional, not recommended)", async () => {
    await seedProject();
    (promptMock as unknown as Mock).mockResolvedValue({
      databaseScripts: "customize",
    });
    (multiselectMock as unknown as Mock).mockResolvedValue([]);

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false },
      makeContext(),
    );

    const options = (multiselectMock as Mock).mock.calls[0][0];
    const values = options.options.map((o: { value: string }) => o.value);
    // Offered in the customize catalogue...
    expect(values).toContain("db:seed");
    // ...with a hint describing what it does.
    const seed = options.options.find(
      (o: { value: string }) => o.value === "db:seed",
    );
    expect(String(seed.hint || seed.label)).toMatch(/seed/i);
    // ...but NOT part of the recommended preselection.
    expect(options.initialValues).not.toContain("db:seed");
  });

  test("db:seed selection adds the script, the seed config and the seed file", async () => {
    await seedProject();

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:generate", "db:seed"],
      },
      makeContext(),
    );

    const final = readManifestFromDisk();
    // The npm script...
    expect(final.scripts["db:seed"]).toBe("prisma db seed");
    // ...the seed command configured where Prisma 7's `db seed` reads it:
    // migrations.seed in the prisma7.config.ts file — NOT a `prisma.seed`
    // field in package.json (that field is only read by the init flow's
    // "Seed the database?" prompt, never by db seed)...
    const config = readPrismaConfig();
    expect(config).toContain(`seed: "tsx prisma/seed.ts"`);
    expect(final.prisma).toBeUndefined();
    // ...the seed skeleton itself (DXG-owned, via the template mechanism)...
    expect(fsMockStore._files.has("prisma/seed.ts")).toBe(true);
    const seedFile = fsMockStore._files.get("prisma/seed.ts")!;
    // ...importing the shared Prisma Client from lib/prisma.ts...
    expect(seedFile).toContain(`from "../lib/prisma"`);
    // ...and tsx lands in devDependencies (it runs the seed file).
    expect(final.devDependencies.tsx).toBeDefined();
    // Unrelated manifest fields stay intact.
    expect(final.name).toBe("my-app");
    expect(final.dependencies.next).toBe("16.2.12");
  });

  test("db:seed is fully idempotent on re-run (script, config, file)", async () => {
    await seedProject();
    const answers = {
      provider: "postgresql",
      installPrismaSkills: false,
      databaseScripts: ["db:generate", "db:seed"],
    };
    const context = makeContext();
    await databaseGenerator.run(answers, context);
    const writesAfterFirst = (fs.writeJson as Mock).mock.calls.length;
    const first = readManifestFromDisk();
    const firstConfig = readPrismaConfig();

    await databaseGenerator.run(answers, context);
    const second = readManifestFromDisk();
    const secondConfig = readPrismaConfig();

    // No duplicate seed config, no second write for identical content.
    expect((fs.writeJson as Mock).mock.calls.length).toBe(writesAfterFirst);
    expect(second).toEqual(first);
    expect(secondConfig).toBe(firstConfig);
    // Exactly one seed line in the config — never duplicated.
    expect(secondConfig.match(/seed:/g)).toHaveLength(1);
    // The seed file itself follows the template idempotence rules
    // (identical content → skipped, never duplicated).
    const summary = operationSummary(2);
    expect(summary.toLowerCase()).toContain("already exists");
  });

  test("existing migrations.seed config is never overwritten without force", async () => {
    await seedProject();
    // The user customized the seed command in their Prisma config.
    const custom = fsMockStore._prismaInitConfig.replace(
      '    path: "prisma/migrations",',
      '    path: "prisma/migrations",\n    seed: "node custom-seed.js",',
    );
    fsMockStore._files.set("prisma7.config.ts", custom);

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:seed"],
      },
      makeContext(),
    );

    // The user's own seed config is preserved verbatim...
    expect(readPrismaConfig()).toBe(custom);
    // ...and the conflict is reported in the summary.
    const summary = operationSummary();
    expect(summary).toContain("node custom-seed.js");
    expect(summary.toLowerCase()).toContain("conflict");
  });

  test("--force replaces a conflicting migrations.seed with the DXG command", async () => {
    await seedProject();
    const custom = fsMockStore._prismaInitConfig.replace(
      '    path: "prisma/migrations",',
      '    path: "prisma/migrations",\n    seed: "node custom-seed.js",',
    );
    fsMockStore._files.set("prisma7.config.ts", custom);

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:seed"],
      },
      makeContext({ force: true }),
    );

    // The DXG seed command replaced the user's, in the same migrations
    // block — the rest of the config survives untouched.
    const config = readPrismaConfig();
    expect(config).toContain(`seed: "tsx prisma/seed.ts"`);
    expect(config).not.toContain("node custom-seed.js");
    expect(config).toContain('url: process.env["DATABASE_URL"]');
    // The replacement is reported as an update.
    const summary = operationSummary();
    expect(summary.toLowerCase()).toContain("migrations.seed");
  });

  test("the seed transform preserves the prisma init config byte-for-byte except migrations.seed", async () => {
    await seedProject();

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:seed"],
      },
      makeContext(),
    );

    const config = readPrismaConfig();
    // The expected result: the prisma init config with ONLY the seed line
    // added inside the existing migrations block.
    const expected = fsMockStore._prismaInitConfig.replace(
      '    path: "prisma/migrations",',
      '    path: "prisma/migrations",\n    seed: "tsx prisma/seed.ts",',
    );
    expect(config).toBe(expected);
    // Every part of the Prisma-owned config survives verbatim:
    expect(config).toContain("// This file was generated by Prisma");
    expect(config).toContain('import "dotenv/config";');
    expect(config).toContain('import { defineConfig } from "prisma/config";');
    expect(config).toContain('schema: "prisma/schema.prisma"');
    expect(config).toContain('path: "prisma/migrations"');
    // ...including the exact datasource URL form prisma init wrote.
    expect(config).toContain('url: process.env["DATABASE_URL"]');
    // The env() form and its import are never introduced.
    expect(config).not.toContain('env("DATABASE_URL")');
    expect(config).not.toMatch(/import\s*\{[^}]*env[^}]*\}\s*from\s*["']prisma\/config["']/);
  });

  test("a user-configured prisma.seed in package.json is left alone (no removal, no addition)", async () => {
    await seedProject({
      ...MY_APP_PACKAGE_JSON,
      prisma: { seed: "node custom-seed.js" },
    });

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:seed"],
      },
      makeContext(),
    );

    // DXG never writes prisma.seed into package.json (Prisma 7's db seed
    // reads migrations.seed from the config file), and never removes a
    // user's existing field — the DXG/user distinction is not reliable
    // enough to auto-delete, so the field is left as the user wrote it.
    const final = readManifestFromDisk();
    expect(final.prisma).toEqual({ seed: "node custom-seed.js" });
    // The Prisma 7 contract is still applied: the config file receives
    // the seed entry.
    expect(readPrismaConfig()).toContain(`seed: "tsx prisma/seed.ts"`);
  });

  test("recommended set still excludes db:seed (opt-in only)", async () => {
    await seedProject();

    await databaseGenerator.run(
      { provider: "postgresql", installPrismaSkills: false, databaseScripts: "recommended" },
      makeContext(),
    );

    const final = readManifestFromDisk();
    expect(final.scripts["db:seed"]).toBeUndefined();
    // No seed command in the Prisma config either, and no prisma section
    // in package.json (the seed phase never runs).
    const config = readPrismaConfig();
    expect(config).toBe(fsMockStore._prismaInitConfig);
    expect(final.prisma).toBeUndefined();
    expect(fsMockStore._files.has("prisma/seed.ts")).toBe(false);
  });

  test("dry-run never creates the seed file nor the seed config", async () => {
    await seedProject();
    const before = fsMockStore._files.get("package.json");

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:seed"],
      },
      makeContext({ dryRun: true }),
    );

    expect(fsMockStore._files.get("package.json")).toBe(before);
    expect(fsMockStore._files.has("prisma/seed.ts")).toBe(false);
    expect(fs.writeJson).not.toHaveBeenCalled();
    // The Prisma config was never written (prisma init is simulated as a
    // no-op here — dry-run never executes commands), and no seed entry
    // could have been planned against it.
    expect(fsMockStore._files.has("prisma7.config.ts")).toBe(false);
    const summary = operationSummary();
    expect(summary).toContain("db:seed");
    // The dry-run plan names the Prisma 7 config file correctly.
    expect(summary).toContain("prisma7.config.ts");
  });

  test("a conflicting migrations.seed still leaves the other seed pieces coherent", async () => {
    await seedProject();
    const custom = fsMockStore._prismaInitConfig.replace(
      '    path: "prisma/migrations",',
      '    path: "prisma/migrations",\n    seed: "node custom-seed.js",',
    );
    fsMockStore._files.set("prisma7.config.ts", custom);

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:generate", "db:seed"],
      },
      makeContext(),
    );

    // The conflict blocks ONLY the config mutation — the other pieces of
    // the seed contract still land (no partial no-op, no partial clobber):
    // the db:seed npm script...
    const final = readManifestFromDisk();
    expect(final.scripts["db:seed"]).toBe("prisma db seed");
    expect(final.scripts["db:generate"]).toBe("prisma generate");
    // ...the seed file skeleton...
    expect(fsMockStore._files.has("prisma/seed.ts")).toBe(true);
    // ...the tsx runner...
    expect(final.devDependencies.tsx).toBeDefined();
    // ...while the user's config entry is preserved verbatim.
    expect(readPrismaConfig()).toBe(custom);
    // Both facts are visible in the summary (conflict + additions).
    const summary = operationSummary();
    expect(summary.toLowerCase()).toContain("conflict");
    expect(summary).toContain("node custom-seed.js");
  });

  test("an existing identical migrations.seed is reported as already satisfied", async () => {
    await seedProject();
    // A previous DXG run (or an identical user choice) already configured
    // the exact same seed command.
    const preConfigured = fsMockStore._prismaInitConfig.replace(
      '    path: "prisma/migrations",',
      '    path: "prisma/migrations",\n    seed: "tsx prisma/seed.ts",',
    );
    fsMockStore._files.set("prisma7.config.ts", preConfigured);
    const manifest = {
      ...MY_APP_PACKAGE_JSON,
      scripts: {
        ...MY_APP_PACKAGE_JSON.scripts,
        "db:seed": "prisma db seed",
      },
    };
    await seedProject(manifest);

    await databaseGenerator.run(
      {
        provider: "postgresql",
        installPrismaSkills: false,
        databaseScripts: ["db:seed"],
      },
      makeContext(),
    );

    // Identical → already satisfied: no write to the config, no
    // duplication, no conflict.
    const config = readPrismaConfig();
    expect(config).toBe(preConfigured);
    expect(config.match(/seed:/g)).toHaveLength(1);
    const final = readManifestFromDisk();
    expect(final.scripts["db:seed"]).toBe("prisma db seed");
    const summary = operationSummary();
    expect(summary.toLowerCase()).not.toContain("conflict");
    expect(summary.toLowerCase()).toContain("already exists");
  });
});
